"""Composition-seam study: what the stage-rating error does to the composition.

The three mechanism curves are composed on one stage axis, but they do not all
read that axis the same way. Uemura's overflow model carries the paper Eq. (10)
stage-rating error as an additive per-draw term on the water level, so its
argument is *the stage a rating relation would report*. The piping branch takes
the same argument as *the realized stage at the levee*. Composing the curves as
received therefore joins two slightly different readings of one axis. Until now
that seam was bounded only by analogy with the Phase 2 record-reconstruction
sensitivity. This driver measures it.

Method
------
The rating-error term is drawn inside the overflow model from per-segment mean
and standard deviation fields (``wl_err_mu_m`` / ``wl_err_sigma_m``), so an arm
with the term suppressed is a small and well-defined change:
``draw_overflow(..., include_rating_error=False)`` zeroes the drawn vector while
leaving the crest and turf-critical-velocity draws on the identical random
stream. The committed companion curve set
``uemura_surface_curves_overflow_no_rating_error.csv`` is that arm, generated by
``scripts/generate_uemura_surface_curves.py`` alongside the primary set.

This driver then recomposes and re-annualises with the companion overflow curves
overlaid on the otherwise unchanged primary surface set, exactly the way the
campaign's ``scour_script_k`` and ``overflow_sine30h`` variants are handled, and
reports:

1. the annual overflow contribution, the annual system probability and the
   mechanism shares at the four characterized cross-sections in both climates;
2. whether the KP 62.0 warming crossing between piping and overflow survives
   (its production margin is a factor of 1.0013, so it is the one ordering in
   the reach that a small displacement could plausibly flip);
3. the reach-wide dominant-mechanism counts, because the seam acts on the
   overflow branch at all 114 segments and not only at the four.

Gate
----
The primary arm is recomposed from the committed CSVs and asserted equal to the
production ``rq4_annual.csv`` rows before any companion number is reported. A
drifted baseline invalidates every displacement below, so the driver refuses
rather than reporting against one.

The composition and annualisation are **imported from the campaign driver**, not
re-implemented: a second copy could drift from the code that produced the
production table this study is a displacement against.

Direction, read from the inputs before running: both gauges carry a *negative*
mean rating error (-0.160 m on the Tokachi, -0.051 m on the Satsunai; ADR-0042
decision 6 as amended 2026-07-22), so the published model evaluates a water
level below the conditioning stage. Suppressing the term raises the effective
level, and the expected sign is therefore *more* overflow, not less. The
standard deviation acts the other way in the deep tail, where a spread term
carries mass over the crest that a point value does not, so the net sign is not
decided by the mean alone and is left to the measurement.

Usage (from the repo root, venv active)::

    python scripts/composition_seam_rating_error_study.py
    python scripts/composition_seam_rating_error_study.py --allow-unverified
"""

from __future__ import annotations

import argparse
import csv
import importlib.util
import json
import sys
import time
from pathlib import Path
from typing import Any

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))

from system_integration.annualize import annualize  # noqa: E402
from system_integration.hazard import load_reach_hazard  # noqa: E402
from system_integration.segments import (  # noqa: E402
    build_registry,
    load_section_table,
)
from system_integration.surface_curves import (  # noqa: E402
    SurfaceCurveSet,
    load_surface_curves,
)
from system_integration.uemura_models import load_segment_inputs  # noqa: E402


def _load_campaign_module():
    """Import the Phase 3 campaign driver for its composition helpers.

    ``_compose_segment`` and ``_bep_path`` are the code that produced the
    production table this study measures a displacement against; a second copy
    could drift from it. Same ``importlib`` route the other cross-driver
    imports in this repo use. ``main()`` is guarded, so importing runs nothing.
    """
    path = REPO / "scripts" / "phase3_campaign.py"
    spec = importlib.util.spec_from_file_location("phase3_campaign", path)
    if spec is None or spec.loader is None:  # pragma: no cover - defensive
        raise ImportError(f"cannot import {path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


_CAMPAIGN = _load_campaign_module()

CURVE_DIR = REPO / "data/processed/uemura_surface_curves"
COMPANION_FILE = CURVE_DIR / "uemura_surface_curves_overflow_no_rating_error.csv"
PRODUCTION_ANNUAL = REPO / "results/system_integration/phase3/rq4_annual.csv"
OUT_DIR = REPO / "results/system_integration/composition_seam"
JSON_OUT = REPO / "docs/decisions/composition-seam-rating-error.json"

#: The primary production configuration these displacements are measured on.
D70 = "matrix"
BEP_SOURCE = "posterior"
LAMBDA_AC_M = 250.0
SEGMENT_LENGTH_M = 200.0

#: Absolute tolerance on the baseline gate. The recomposition is deterministic
#: and should reproduce the production row exactly; this allows only for the
#: decimal round trip through the CSV.
GATE_ATOL = 1e-12

MECHANISMS = ("bep", "overflow", "fluvial_scour")


def _production_rows() -> dict[tuple[float, str], dict[str, str]]:
    """The production primary rows at the four BEP segments, keyed (kp, scenario)."""
    rows: dict[tuple[float, str], dict[str, str]] = {}
    with open(PRODUCTION_ANNUAL, encoding="utf-8") as handle:
        for row in csv.DictReader(handle):
            if (
                row["d70"] == D70
                and row["bep_source"] == BEP_SOURCE
                and float(row["lambda_ac_m"]) == LAMBDA_AC_M
                and row["surface_variant"] == "primary"
                and row["mechanisms"].startswith("bep")
            ):
                rows[(float(row["kp"]), row["scenario"])] = row
    if not rows:
        raise SystemExit(
            f"{PRODUCTION_ANNUAL}: no primary posterior-matrix BEP rows found."
        )
    return rows


def _surface_sets() -> dict[str, SurfaceCurveSet]:
    """The primary set, and the companion overflow curves overlaid on it."""
    parts = [load_surface_curves(path) for path in _CAMPAIGN.PRIMARY_FILES]
    primary = SurfaceCurveSet(
        curves=tuple(c for part in parts for c in part.curves),
        source="uemura_csv",
    )
    if not COMPANION_FILE.exists():
        raise SystemExit(
            f"{COMPANION_FILE.name} is missing. Run "
            "scripts/generate_uemura_surface_curves.py first."
        )
    companion = load_surface_curves(COMPANION_FILE)
    if any(c.mechanism != "overflow" for c in companion.curves):
        raise SystemExit("the companion set must vary the overflow mechanism only.")
    kept = [c for c in primary.curves if c.mechanism != "overflow"]
    arm = SurfaceCurveSet(
        curves=tuple(kept) + companion.curves,
        source="uemura_csv+overflow_no_rating_error",
    )
    return {"primary": primary, "no_rating_error": arm}


def _annual_entry(annual, mechanisms: tuple[str, ...]) -> dict[str, Any]:
    entry: dict[str, Any] = {"p_annual_system": float(annual.p_f_annual_system)}
    for mech in MECHANISMS:
        entry[f"p_annual_{mech}"] = (
            float(annual.p_f_annual_per_mechanism.get(mech, 0.0))
            if mech in mechanisms
            else None
        )
        entry[f"share_{mech}"] = (
            float(annual.dominance_share(mech)) if mech in mechanisms else None
        )
    return entry


def _fmt(value: float | None, spec: str) -> str:
    """Format a possibly-None displacement for the console table."""
    return (
        "n/d".rjust(int(spec.split(".")[0])) if value is None else format(value, spec)
    )


def _rating_error_inputs(seg_inputs) -> dict[str, Any]:
    """The rating-error mean and spread actually in force, per river.

    The term is per segment, but it is constant within a river (each river
    inherits its own gauge: Tokachi from Obihiro, Satsunai from Nantai;
    ADR-0042 decision 6 as amended 2026-07-22). Recorded as the distinct pairs
    found, so a future per-segment differentiation shows up here as more than
    one entry rather than being silently averaged away.
    """
    per_river: dict[str, list[tuple[float, float]]] = {}
    for (river, _kp), seg in seg_inputs.items():
        pair = (float(seg.wl_err_mu_m), float(seg.wl_err_sigma_m))
        if pair not in per_river.setdefault(river, []):
            per_river[river].append(pair)
    return {
        river: [{"wl_err_mu_m": mu, "wl_err_sigma_m": sigma} for mu, sigma in pairs]
        for river, pairs in sorted(per_river.items())
    }


def _relative(arm: float | None, base: float | None) -> float | None:
    if arm is None or base is None or base == 0.0:
        return None
    return float(arm / base)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--allow-unverified",
        action="store_true",
        help="Report even if the primary arm does not reproduce production.",
    )
    args = parser.parse_args(argv)

    t0 = time.time()
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    registry = load_section_table(
        _CAMPAIGN.SECTION_TABLE, build_registry(_CAMPAIGN.DATA_ROOT), allow_gaps=True
    )
    seg_inputs = load_segment_inputs(_CAMPAIGN.SEGMENT_INPUTS)
    surfaces = _surface_sets()
    production = _production_rows()

    bep_curves = {}
    for segment in registry.bep_segments():
        bep_curves[segment.kp] = _CAMPAIGN.load_bep_curve(
            _CAMPAIGN._bep_path(segment.kp, D70, BEP_SOURCE), branch="transient"
        )

    nodes = []
    for s in registry.segments:
        if s.bep_source_kp is not None:
            datum = bep_curves[s.kp].datum_m
        else:
            datum = seg_inputs[(s.river, round(s.kp, 3))].ground_m_msl
        nodes.append((s.river, s.kp, datum))
    hazards = {}
    for scenario in _CAMPAIGN.SCENARIOS:
        print(f"hazard: {scenario} ({time.time() - t0:.0f}s)", flush=True)
        hazards[scenario] = load_reach_hazard(
            _CAMPAIGN.DATA_ROOT,
            nodes=nodes,
            scenario=scenario,
            cache_dir=_CAMPAIGN.HAZARD_CACHE,
        )

    n_eff = max(1.0, SEGMENT_LENGTH_M / LAMBDA_AC_M)

    # --- compose and annualise both arms over every segment ------------------
    results: dict[str, dict] = {arm: {} for arm in surfaces}
    dominance: dict[str, dict[str, dict[str, int]]] = {
        arm: {scen: {} for scen in _CAMPAIGN.SCENARIOS} for arm in surfaces
    }
    for arm, surface in surfaces.items():
        print(f"composing arm {arm} ({time.time() - t0:.0f}s)", flush=True)
        for segment in registry.segments:
            key = (segment.river, round(segment.kp, 3))
            bep = (
                bep_curves.get(segment.kp)
                if segment.bep_source_kp is not None
                else None
            )
            frag, _clamped = _CAMPAIGN._compose_segment(
                segment, surface, bep, n_eff, "historical"
            )
            if frag is None:
                continue
            for scenario in _CAMPAIGN.SCENARIOS:
                annual = annualize(frag, hazards[scenario][key])
                if segment.bep_source_kp is not None:
                    results[arm].setdefault(scenario, {})[segment.kp] = _annual_entry(
                        annual, frag.mechanisms
                    )
                contributions = {
                    mech: float(annual.p_f_annual_per_mechanism.get(mech, 0.0))
                    for mech in frag.mechanisms
                }
                top = max(contributions, key=lambda m: contributions[m])
                label = top if contributions[top] > 0.0 else "no mechanism loaded"
                counts = dominance[arm][scenario]
                counts[label] = counts.get(label, 0) + 1

    # --- the gate -------------------------------------------------------------
    gate_failures = []
    for (kp, scenario), row in production.items():
        got = results["primary"][scenario][kp]
        for field in ("p_annual_system", "p_annual_bep", "p_annual_overflow"):
            expected = float(row[field])
            actual = got[field]
            if actual is None or abs(actual - expected) > max(
                GATE_ATOL, 1e-9 * abs(expected)
            ):
                gate_failures.append(
                    f"KP{kp:g} {scenario} {field}: recomposed {actual!r} vs "
                    f"production {expected!r}"
                )
    if gate_failures:
        message = (
            "the primary arm does not reproduce the production rq4_annual.csv "
            "rows; every displacement below would be measured against a drifted "
            "baseline:\n  " + "\n  ".join(gate_failures)
        )
        if not args.allow_unverified:
            raise SystemExit(message)
        print("UNVERIFIED: " + message, flush=True)
        gate_status = "UNVERIFIED"
    else:
        gate_status = "reproduces_production"

    # --- assemble the comparison ---------------------------------------------
    sections: list[dict[str, Any]] = []
    for scenario in _CAMPAIGN.SCENARIOS:
        for kp in sorted(results["primary"][scenario]):
            base = results["primary"][scenario][kp]
            arm = results["no_rating_error"][scenario][kp]
            sections.append(
                {
                    "kp": kp,
                    "scenario": scenario,
                    "primary": base,
                    "no_rating_error": arm,
                    "displacement": {
                        "p_annual_system": _relative(
                            arm["p_annual_system"], base["p_annual_system"]
                        ),
                        "p_annual_overflow": _relative(
                            arm["p_annual_overflow"], base["p_annual_overflow"]
                        ),
                        "p_annual_bep": _relative(
                            arm["p_annual_bep"], base["p_annual_bep"]
                        ),
                        "delta_share_bep": (
                            None
                            if base["share_bep"] is None
                            else float(arm["share_bep"] - base["share_bep"])
                        ),
                        "delta_share_overflow": (
                            None
                            if base["share_overflow"] is None
                            else float(arm["share_overflow"] - base["share_overflow"])
                        ),
                    },
                }
            )

    # --- the KP 62.0 warming crossing ----------------------------------------
    crossing = {}
    for arm in surfaces:
        entry = results[arm]["+4K"][62.0]
        bep = entry["p_annual_bep"]
        overflow = entry["p_annual_overflow"]
        crossing[arm] = {
            "p_annual_bep": bep,
            "p_annual_overflow": overflow,
            "margin_bep_over_overflow": _relative(bep, overflow),
            "dominant": "bep" if bep > overflow else "overflow",
            "share_bep": entry["share_bep"],
            "share_overflow": entry["share_overflow"],
        }
    crossing["survives"] = bool(
        crossing["primary"]["dominant"] == crossing["no_rating_error"]["dominant"]
    )

    payload = {
        "study": "composition-seam-rating-error",
        "date": "2026-08-21",
        "description": (
            "Direct measurement of the composition seam between the surface "
            "curves, whose argument carries the Eq. (10) stage-rating error, "
            "and the piping curve, whose argument is the realized stage. The "
            "arm suppresses the rating-error term inside the overflow model "
            "and recomposes; it is a labeled sensitivity companion and does "
            "not change the production deliverable."
        ),
        "configuration": {
            "d70": D70,
            "bep_source": BEP_SOURCE,
            "lambda_ac_m": LAMBDA_AC_M,
            "surface_arms": {arm: s.source for arm, s in surfaces.items()},
            "companion_file": str(COMPANION_FILE.relative_to(REPO)).replace("\\", "/"),
        },
        "gate": {
            "status": gate_status,
            "checked_rows": len(production),
            "failures": gate_failures,
        },
        "rating_error_inputs": _rating_error_inputs(seg_inputs),
        "sections": sections,
        "kp62_warming_crossing": crossing,
        "reach_dominance_counts": dominance,
        "runtime_s": round(time.time() - t0, 1),
    }

    JSON_OUT.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    (OUT_DIR / "composition_seam_rating_error.json").write_text(
        json.dumps(payload, indent=2) + "\n", encoding="utf-8"
    )
    print(f"\nWrote {JSON_OUT.relative_to(REPO)}  (gate: {gate_status})")

    print(
        f"\n{'KP':>6s} {'scenario':>10s} "
        f"{'sys base':>11s} {'sys arm':>11s} {'x':>7s} "
        f"{'ovf base':>11s} {'ovf arm':>11s} {'x':>8s} "
        f"{'share_bep':>10s} {'-> arm':>8s}"
    )
    for entry in sections:
        d = entry["displacement"]
        print(
            f"{entry['kp']:6.1f} {entry['scenario']:>10s} "
            f"{entry['primary']['p_annual_system']:11.4e} "
            f"{entry['no_rating_error']['p_annual_system']:11.4e} "
            f"{d['p_annual_system']:7.3f} "
            f"{entry['primary']['p_annual_overflow']:11.4e} "
            f"{entry['no_rating_error']['p_annual_overflow']:11.4e} "
            f"{_fmt(d['p_annual_overflow'], '8.3f')} "
            f"{entry['primary']['share_bep']:10.4f} "
            f"{entry['no_rating_error']['share_bep']:8.4f}"
        )
    print(
        "\nKP 62.0 +4K crossing: "
        f"primary margin {crossing['primary']['margin_bep_over_overflow']:.4f} "
        f"({crossing['primary']['dominant']}), arm margin "
        f"{crossing['no_rating_error']['margin_bep_over_overflow']:.4f} "
        f"({crossing['no_rating_error']['dominant']}) -> "
        f"{'SURVIVES' if crossing['survives'] else 'FLIPS'}"
    )
    for arm, per_scen in dominance.items():
        for scenario, counts in per_scen.items():
            print(f"reach dominance [{arm}][{scenario}]: {counts}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
